[
  { "id": 1, "name": "Le Monde", "slug": "le-monde", "domains": ["lemonde.fr"], "aliases": ["LeMonde", "Le Monde.fr", "le monde"] },
  { "id": 2, "name": "Le Figaro", "slug": "le-figaro", "domains": ["lefigaro.fr"], "aliases": ["LeFigaro", "Le Figaro.fr", "le figaro"] },
  { "id": 3, "name": "Libération", "slug": "liberation", "domains": ["liberation.fr"], "aliases": ["Liberation", "Libé", "Libération.fr"] },
  { "id": 4, "name": "La Croix", "slug": "la-croix", "domains": ["la-croix.com"], "aliases": ["LaCroix", "La Croix.com", "la croix"] },
  { "id": 5, "name": "L’Humanité", "slug": "l-humanite", "domains": ["humanite.fr"], "aliases": ["LHumanite", "L'Humanité", "Humanité"] },
  { "id": 6, "name": "Le Parisien / Aujourd’hui en France", "slug": "le-parisien", "domains": ["leparisien.fr"], "aliases": ["Le Parisien", "Aujourd'hui en France", "leparisien"] },
  { "id": 7, "name": "Les Échos", "slug": "les-echos", "domains": ["lesechos.fr"], "aliases": ["Les Echos", "LesEchos", "les échos"] },
  { "id": 8, "name": "L’Opinion", "slug": "lopinion", "domains": ["lopinion.fr"], "aliases": ["LOpinion", "L'Opinion", "L Opinion"] },
  { "id": 9, "name": "La Tribune", "slug": "la-tribune", "domains": ["latribune.fr"], "aliases": ["LaTribune", "La Tribune.fr", "la tribune"] },
  { "id": 10, "name": "L’Agefi", "slug": "lagefi", "domains": [], "aliases": ["LAgefi", "L'Agefi", "Agefi"] },
  { "id": 11, "name": "Le Canard enchaîné", "slug": "le-canard-enchaine", "domains": [], "aliases": ["Le Canard enchaine", "Le Canard Enchaîné", "Canard enchaîné"] },
  { "id": 12, "name": "Charlie Hebdo", "slug": "charlie-hebdo", "domains": ["charliehebdo.fr"], "aliases": ["CharlieHebdo", "Charlie Hebdo.fr", "charlie"] },
  { "id": 13, "name": "Le Point", "slug": "le-point", "domains": ["lepoint.fr"], "aliases": ["LePoint", "Le Point.fr", "le point"] },
  { "id": 14, "name": "L’Obs", "slug": "lobs", "domains": [], "aliases": ["LObs", "L'Obs", "Le Nouvel Obs", "Nouvel Obs"] },
  { "id": 15, "name": "L’Express", "slug": "lexpress", "domains": ["lexpress.fr"], "aliases": ["LExpress", "L'Express", "L Express"] },
  { "id": 16, "name": "Marianne", "slug": "marianne", "domains": ["marianne.net"], "aliases": ["Marianne.net", "marianne"] },
  { "id": 17, "name": "Valeurs actuelles", "slug": "valeurs-actuelles", "domains": ["valeursactuelles.com"], "aliases": ["ValeursActuelles", "VA", "valeurs actuelles"] },
  { "id": 18, "name": "Le Monde diplomatique", "slug": "le-monde-diplomatique", "domains": ["monde-diplomatique.fr"], "aliases": ["Monde Diplo", "Le Diplo", "LeMondeDiplomatique"] },
  { "id": 19, "name": "Courrier international", "slug": "courrier-international", "domains": ["courrierinternational.com"], "aliases": ["CourrierInternational", "Courrier inter", "courrier international"] },
  { "id": 20, "name": "Alternatives Économiques", "slug": "alternatives-economiques", "domains": ["alternatives-economiques.fr"], "aliases": ["Alternatives Economiques", "AlterEco", "Alternatives éco"] },
  { "id": 21, "name": "Politis", "slug": "politis", "domains": ["politis.fr"], "aliases": ["Politis.fr", "politis"] },
  { "id": 22, "name": "Regards", "slug": "regards", "domains": ["regards.fr"], "aliases": ["Regards.fr", "regards"] },
  { "id": 23, "name": "Socialter", "slug": "socialter", "domains": [], "aliases": ["Socialter.fr", "socialter"] },
  { "id": 24, "name": "Fakir", "slug": "fakir", "domains": [], "aliases": ["Fakir Presse", "Fakir mag", "fakir"] },
  { "id": 25, "name": "La Vie", "slug": "la-vie", "domains": [], "aliases": ["LaVie", "La Vie.fr", "la vie"] },
  { "id": 26, "name": "Famille Chrétienne", "slug": "famille-chretienne", "domains": [], "aliases": ["Famille Chretienne", "FamilleChrétienne", "Famille Chrétienne"] },
  { "id": 27, "name": "Mediapart", "slug": "mediapart", "domains": ["mediapart.fr"], "aliases": ["Médiapart", "Mediapart.fr", "mediapart"] },
  { "id": 28, "name": "Arrêt sur images", "slug": "arret-sur-images", "domains": ["arretsurimages.net"], "aliases": ["Arret sur images", "ASI", "Arrêt sur Images"] },
  { "id": 29, "name": "Disclose", "slug": "disclose", "domains": ["disclose.ngo"], "aliases": ["Disclose.ngo", "disclose"] },
  { "id": 30, "name": "StreetPress", "slug": "streetpress", "domains": ["streetpress.com"], "aliases": ["Street Press", "streetpress"] },
  { "id": 31, "name": "Les Jours", "slug": "les-jours", "domains": ["lesjours.fr"], "aliases": ["LesJours", "Les Jours.fr", "les jours"] },
  { "id": 32, "name": "Blast", "slug": "blast", "domains": ["blast-info.fr"], "aliases": ["BLAST", "Blast-info", "blast"] },
  { "id": 33, "name": "Off Investigation", "slug": "off-investigation", "domains": [], "aliases": ["OffInvestigation", "Off Investigation.fr", "off investigation"] },
  { "id": 34, "name": "Médiacités", "slug": "mediacites", "domains": ["mediacites.fr"], "aliases": ["Mediacites", "MédiaCités", "mediacites"] },
  { "id": 35, "name": "Contexte", "slug": "contexte", "domains": [], "aliases": ["Contexte.com", "contexte"] },
  { "id": 36, "name": "Basta!", "slug": "basta", "domains": ["basta.media"], "aliases": ["Basta", "Basta!", "basta"] },
  { "id": 37, "name": "Reporterre", "slug": "reporterre", "domains": ["reporterre.net"], "aliases": ["Reporterre.net", "reporterre"] },
  { "id": 38, "name": "Vert", "slug": "vert", "domains": ["vert.eco"], "aliases": ["Vert le média", "Vert.eco", "vert"] },
  { "id": 39, "name": "The Conversation France", "slug": "the-conversation-france", "domains": ["theconversation.com"], "aliases": ["The Conversation", "TheConversationFR", "The Conversation FR"] },
  { "id": 40, "name": "Slate.fr", "slug": "slate-fr", "domains": ["slate.fr"], "aliases": ["Slate", "Slate.fr", "slate"] },
  { "id": 41, "name": "HuffPost France", "slug": "huffpost-france", "domains": ["huffingtonpost.fr"], "aliases": ["HuffPost", "Huffington Post France", "HuffPost FR"] },

  { "id": 100, "name": "BFM TV", "slug": "bfm-tv", "domains": ["bfmtv.com"], "aliases": ["BFMTV", "BFMTV.com", "BFM"] },
  { "id": 101, "name": "CNews", "slug": "cnews", "domains": ["cnews.fr"], "aliases": ["CNEWS", "CNews.fr", "cnews"] },
  { "id": 102, "name": "LCI", "slug": "lci", "domains": ["lci.fr"], "aliases": ["LCI.fr", "LCI (TF1)", "lci"] },
  { "id": 103, "name": "France 24", "slug": "france-24", "domains": ["france24.com"], "aliases": ["France24", "France 24.com", "france24"] },
  { "id": 104, "name": "RFI", "slug": "rfi", "domains": ["rfi.fr"], "aliases": ["Radio France Internationale", "RFI.fr", "rfi"] },
  { "id": 105, "name": "France Inter", "slug": "france-inter", "domains": ["radiofrance.fr"], "aliases": ["FranceInter", "Radio France Inter", "france inter"] },
  { "id": 106, "name": "Europe 1", "slug": "europe-1", "domains": ["europe1.fr"], "aliases": ["Europe1", "Europe 1.fr", "europe1"] },
  { "id": 107, "name": "RTL", "slug": "rtl", "domains": ["rtl.fr"], "aliases": ["RTL.fr", "rtl"] },
  { "id": 108, "name": "RMC", "slug": "rmc", "domains": ["rmc.bfmtv.com"], "aliases": ["RMC.fr", "RMC (BFM)", "rmc"] },
  { "id": 109, "name": "TF1", "slug": "tf1", "domains": [], "aliases": ["TF1 Info", "TF1info", "tf1"] },
  { "id": 110, "name": "France 2", "slug": "france-2", "domains": ["france.tv"], "aliases": ["France2", "france 2"] },
  { "id": 111, "name": "France 3", "slug": "france-3", "domains": ["france.tv"], "aliases": ["France3", "france 3"] },
  { "id": 112, "name": "M6", "slug": "m6", "domains": ["m6.fr"], "aliases": ["M6.fr", "m6"] },
  { "id": 113, "name": "Arte", "slug": "arte", "domains": ["arte.tv"], "aliases": ["ARTE", "Arte.tv", "arte"] },
  { "id": 114, "name": "France Info", "slug": "france-info", "domains": ["franceinfo.fr"], "aliases": ["Franceinfo", "franceinfo", "France Info TV"] },

  { "id": 200, "name": "HugoDécrypte", "slug": "hugodecrypte", "domains": [], "aliases": ["Hugo Decrypte", "HugoDecrypte", "Hugo Décrypte"] },
  { "id": 201, "name": "Sardoche", "slug": "sardoche", "domains": [], "aliases": ["SardocheTV", "sardoche"] },
  { "id": 202, "name": "Thinkerview", "slug": "thinkerview", "domains": [], "aliases": ["ThinkerView", "thinkerview"] },
  { "id": 203, "name": "Clément Viktorovitch", "slug": "clement-viktorovitch", "domains": [], "aliases": ["Clement Viktorovitch", "Viktorovitch"] },
  { "id": 204, "name": "Pascal Boniface", "slug": "pascal-boniface", "domains": [], "aliases": ["Boniface", "PascalBoniface"] },
  { "id": 205, "name": "Tatiana Ventôse", "slug": "tatiana-ventose", "domains": [], "aliases": ["Tatiana Ventose", "TatianaVentose"] },
  { "id": 206, "name": "Jean Massiet", "slug": "jean-massiet", "domains": [], "aliases": ["JeanMassiet", "massiet"] },
  { "id": 207, "name": "Usul", "slug": "usul", "domains": [], "aliases": ["Usul2000", "usul"] },
  { "id": 208, "name": "Hugo Clément", "slug": "hugo-clement", "domains": [], "aliases": ["Hugo Clement", "HugoClement"] },
  { "id": 209, "name": "Johan Reboul", "slug": "johan-reboul", "domains": [], "aliases": ["JohanReboul", "LeJeuneEngage"] },
  { "id": 210, "name": "Mister Geopolitix", "slug": "mister-geopolitix", "domains": [], "aliases": ["MisterGeopolitix", "Mr Geopolitix"] },
  { "id": 211, "name": "Osons Causer", "slug": "osons-causer", "domains": [], "aliases": ["OsonsCauser", "osons causer"] },
  { "id": 212, "name": "Linguisticae", "slug": "linguisticae", "domains": [], "aliases": ["Linguisticae", "linguisticae"] },
  { "id": 213, "name": "Le Réveilleur", "slug": "le-reveilleur", "domains": [], "aliases": ["Le Reveilleur", "LeReveilleur"] },
  { "id": 214, "name": "Heu?reka", "slug": "heureka", "domains": [], "aliases": ["Heureka", "Heu'reka", "Heu?reka"] },
  { "id": 215, "name": "Stupid Economics", "slug": "stupid-economics", "domains": [], "aliases": ["StupidEconomics", "stupid economics"] },
  { "id": 216, "name": "Le Raptor", "slug": "le-raptor", "domains": [], "aliases": ["Raptor", "LeRaptor"] },
  { "id": 217, "name": "Bon Pote", "slug": "bon-pote", "domains": [], "aliases": ["BonPote", "bon pote"] },
  { "id": 218, "name": "Camille Étienne", "slug": "camille-etienne", "domains": [], "aliases": ["Camille Etienne", "CamilleEtienne"] },
  { "id": 219, "name": "Girl go green", "slug": "girl-go-green", "domains": [], "aliases": ["GirlGoGreen", "Girl go green"] },
  { "id": 220, "name": "Rokhaya Diallo", "slug": "rokhaya-diallo", "domains": [], "aliases": ["RokhayaDiallo", "Diallo"] },
  { "id": 221, "name": "Assa Traoré", "slug": "assa-traore", "domains": [], "aliases": ["Assa Traore", "AssaTraore"] },
  { "id": 222, "name": "Salomé Saqué", "slug": "salome-saque", "domains": [], "aliases": ["Salome Saque", "SalomeSaque"] },
  { "id": 223, "name": "Caroline Fourest", "slug": "caroline-fourest", "domains": [], "aliases": ["CarolineFourest", "Fourest"] },
  { "id": 224, "name": "Papacito", "slug": "papacito", "domains": [], "aliases": ["Papacito", "papacito"] },
  { "id": 225, "name": "Thaïs d’Escufon", "slug": "thais-descufon", "domains": [], "aliases": ["Thais d'Escufon", "ThaisDescufon", "Thaïs d’Escufon"] },
  { "id": 226, "name": "Eugénie Bastié", "slug": "eugenie-bastie", "domains": [], "aliases": ["Eugenie Bastie", "EugenieBastie"] },
  { "id": 227, "name": "Raphaël Enthoven", "slug": "raphael-enthoven", "domains": [], "aliases": ["Raphael Enthoven", "RaphaelEnthoven"] },

  { "id": 300, "name": "Acrimed", "slug": "acrimed", "domains": ["acrimed.org"], "aliases": ["ACRIMED", "acrimed"] },
  { "id": 301, "name": "Lundi matin", "slug": "lundi-matin", "domains": ["lundi.am"], "aliases": ["LundiMatin", "lundi matin"] },
  { "id": 302, "name": "Contrepoints", "slug": "contrepoints", "domains": ["contrepoints.org"], "aliases": ["ContrePoints", "contrepoints"] },
  { "id": 303, "name": "Atlantico", "slug": "atlantico", "domains": ["atlantico.fr"], "aliases": ["Atlantico.fr", "atlantico"] },
  { "id": 304, "name": "Causeur", "slug": "causeur", "domains": ["causeur.fr"], "aliases": ["Causeur.fr", "causeur"] },
  { "id": 305, "name": "L'Incorrect", "slug": "lincorrect", "domains": ["lincorrect.org"], "aliases": ["L Incorrect", "L’Incorrect", "LIncorrect"] },
  { "id": 306, "name": "Le Média", "slug": "le-media", "domains": ["lemediatv.fr"], "aliases": ["LeMedia", "Le Média TV", "lemediatv"] },
  { "id": 307, "name": "Frustration Magazine", "slug": "frustration-magazine", "domains": ["frustrationmagazine.fr"], "aliases": ["Frustration", "FrustrationMag", "Frustration magazine"] },
  { "id": 308, "name": "Splann!", "slug": "splann", "domains": ["splann.org"], "aliases": ["Splann", "Splann!"] },
  { "id": 309, "name": "Marsactu", "slug": "marsactu", "domains": ["marsactu.fr"], "aliases": ["Marsactu.fr", "marsactu"] },
  { "id": 310, "name": "Next.ink", "slug": "next-ink", "domains": ["next.ink"], "aliases": ["Next", "NextInk", "next.ink"] },
  { "id": 311, "name": "Reflets.info", "slug": "reflets", "domains": ["reflets.info"], "aliases": ["Reflets", "Reflets.info"] },
  { "id": 312, "name": "Rue89 Bordeaux", "slug": "rue89-bordeaux", "domains": ["rue89bordeaux.com"], "aliases": ["Rue89Bordeaux", "Rue 89 Bordeaux"] },
  { "id": 313, "name": "Rue89 Lyon", "slug": "rue89-lyon", "domains": ["rue89lyon.fr"], "aliases": ["Rue89Lyon", "Rue 89 Lyon"] },
  { "id": 314, "name": "Rue89 Strasbourg", "slug": "rue89-strasbourg", "domains": ["rue89strasbourg.com"], "aliases": ["Rue89Strasbourg", "Rue 89 Strasbourg"] },
  { "id": 315, "name": "AOC", "slug": "aoc", "domains": ["aoc.media"], "aliases": ["AOC Media", "AOC.media"] },
  { "id": 316, "name": "Le Grand Continent", "slug": "le-grand-continent", "domains": ["legrandcontinent.eu"], "aliases": ["Grand Continent", "LeGrandContinent"] },
  { "id": 317, "name": "Brief.me", "slug": "brief-me", "domains": ["brief.me"], "aliases": ["Brief", "Brief.me"] },
  { "id": 318, "name": "XXI", "slug": "xxi", "domains": ["revue21.fr"], "aliases": ["Revue XXI", "XXI magazine"] },
  { "id": 319, "name": "Orient XXI", "slug": "orient-xxi", "domains": ["orientxxi.info"], "aliases": ["OrientXXI", "Orient 21"] },
  { "id": 320, "name": "Les Surligneurs", "slug": "les-surligneurs", "domains": ["lessurligneurs.eu"], "aliases": ["Surligneurs", "LesSurligneurs"] },
  { "id": 321, "name": "Conspiracy Watch", "slug": "conspiracy-watch", "domains": ["conspiracywatch.info"], "aliases": ["ConspiracyWatch", "conspiracy watch"] },
  { "id": 322, "name": "Le Vent Se Lève (LVSL)", "slug": "lvsl", "domains": ["lvsl.fr"], "aliases": ["LVSL", "Le Vent Se Leve", "Le Vent se lève"] },
  { "id": 323, "name": "Révolution Permanente", "slug": "revolution-permanente", "domains": ["revolutionpermanente.fr"], "aliases": ["Revolution Permanente", "RP", "Révolution Permanente"] },
  { "id": 324, "name": "Terrestres", "slug": "terrestres", "domains": ["terrestres.org"], "aliases": ["Terrestres.org", "terrestres"] },
  { "id": 325, "name": "Mediabask", "slug": "mediabask", "domains": ["mediabask.eus"], "aliases": ["MédiaBask", "Mediabask.eus"] },
  { "id": 326, "name": "Le Ravi", "slug": "le-ravi", "domains": ["leravi.fr"], "aliases": ["LeRavi", "Le Ravi.fr"] },
  { "id": 327, "name": "La Revue Dessinée", "slug": "la-revue-dessinee", "domains": ["larevuedessinee.fr"], "aliases": ["Revue Dessinée", "LaRevueDessinee"] },
  { "id": 328, "name": "La Déferlante", "slug": "la-deferlante", "domains": ["revueladeferlante.fr"], "aliases": ["La Deferlante", "Revue La Déferlante"] },
  { "id": 329, "name": "Le Drenche", "slug": "le-drenche", "domains": ["ledrenche.fr"], "aliases": ["LeDrenche", "ledrenche"] },

  { "id": 400, "name": "Emmanuel Macron", "slug": "emmanuel-macron", "domains": [], "aliases": ["@EmmanuelMacron", "EmmanuelMacron"] },
  { "id": 401, "name": "Gabriel Attal", "slug": "gabriel-attal", "domains": [], "aliases": ["@GabrielAttal", "GabrielAttal"] },
  { "id": 402, "name": "Gérald Darmanin", "slug": "gerald-darmanin", "domains": [], "aliases": ["@GDarmanin", "Gerald Darmanin"] },
  { "id": 403, "name": "Élisabeth Borne", "slug": "elisabeth-borne", "domains": [], "aliases": ["@Elisabeth_Borne", "Elisabeth Borne"] },
  { "id": 404, "name": "Édouard Philippe", "slug": "edouard-philippe", "domains": [], "aliases": ["@EPhilippe_LH", "Edouard Philippe"] },
  { "id": 405, "name": "François Bayrou", "slug": "francois-bayrou", "domains": [], "aliases": ["@bayrou", "Francois Bayrou"] },
  { "id": 406, "name": "Bruno Le Maire", "slug": "bruno-le-maire", "domains": [], "aliases": ["@BrunoLeMaire", "BrunoLeMaire"] },
  { "id": 407, "name": "Yaël Braun-Pivet", "slug": "yael-braun-pivet", "domains": [], "aliases": ["@YaelBRAUNPIVET", "Yael Braun-Pivet"] },
  { "id": 408, "name": "Aurore Bergé", "slug": "aurore-berge", "domains": [], "aliases": ["@auroreberge", "Aurore Berge"] },
  { "id": 409, "name": "Raphaël Glucksmann", "slug": "raphael-glucksmann", "domains": [], "aliases": ["@rglucks1", "Raphael Glucksmann"] },
  { "id": 410, "name": "Olivier Faure", "slug": "olivier-faure", "domains": [], "aliases": ["@faureolivier", "OlivierFaure"] },
  { "id": 411, "name": "Marine Tondelier", "slug": "marine-tondelier", "domains": [], "aliases": ["@marinetondelier", "MarineTondelier"] },
  { "id": 412, "name": "Fabien Roussel", "slug": "fabien-roussel", "domains": [], "aliases": ["@Fabien_Roussel", "FabienRoussel"] },
  { "id": 413, "name": "Jean-Luc Mélenchon", "slug": "jean-luc-melenchon", "domains": [], "aliases": ["@JLMelenchon", "JLMelenchon", "Jean Luc Melenchon"] },
  { "id": 414, "name": "Manuel Bompard", "slug": "manuel-bompard", "domains": [], "aliases": ["@mbompard", "ManuelBompard"] },
  { "id": 415, "name": "Mathilde Panot", "slug": "mathilde-panot", "domains": [], "aliases": ["@MathildePanot", "MathildePanot"] },
  { "id": 416, "name": "François Ruffin", "slug": "francois-ruffin", "domains": [], "aliases": ["@Francois_Ruffin", "Francois Ruffin"] },
  { "id": 417, "name": "Sandrine Rousseau", "slug": "sandrine-rousseau", "domains": [], "aliases": ["@sandrousseau", "SandrineRousseau"] },
  { "id": 418, "name": "Anne Hidalgo", "slug": "anne-hidalgo", "domains": [], "aliases": ["@Anne_Hidalgo", "AnneHidalgo"] },
  { "id": 419, "name": "Valérie Pécresse", "slug": "valerie-pecresse", "domains": [], "aliases": ["@vpecresse", "Valerie Pecresse"] },
  { "id": 420, "name": "Laurent Wauquiez", "slug": "laurent-wauquiez", "domains": [], "aliases": ["@laurentwauquiez", "LaurentWauquiez"] },
  { "id": 421, "name": "Bruno Retailleau", "slug": "bruno-retailleau", "domains": [], "aliases": ["@BrunoRetailleau", "BrunoRetailleau"] },
  { "id": 422, "name": "Éric Ciotti", "slug": "eric-ciotti", "domains": [], "aliases": ["@eciotti", "Eric Ciotti"] },
  { "id": 423, "name": "Marine Le Pen", "slug": "marine-le-pen", "domains": [], "aliases": ["@MLP_officiel", "MarineLePen"] },
  { "id": 424, "name": "Jordan Bardella", "slug": "jordan-bardella", "domains": [], "aliases": ["@J_Bardella", "JordanBardella"] },
  { "id": 425, "name": "Éric Zemmour", "slug": "eric-zemmour", "domains": [], "aliases": ["@ZemmourEric", "Eric Zemmour"] },
  { "id": 426, "name": "Marion Maréchal", "slug": "marion-marechal", "domains": [], "aliases": ["@MarionMarechal", "Marion Marechal"] },
  { "id": 427, "name": "Nicolas Dupont-Aignan", "slug": "nicolas-dupont-aignan", "domains": [], "aliases": ["@dupontaignan", "Dupont-Aignan", "NDA"] },
  { "id": 428, "name": "François Hollande", "slug": "francois-hollande", "domains": [], "aliases": ["@fhollande", "Francois Hollande"] },
  { "id": 429, "name": "François-Xavier Bellamy", "slug": "francois-xavier-bellamy", "domains": [], "aliases": ["@fxbellamy", "FX Bellamy", "Francois Xavier Bellamy"] }
]
